---
version: "3"
services:
  syncfuse:
    build: ../
    #image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://syncfuse:syncfuse@db:5432/syncfuse
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: syncfuse
      POSTGRES_USER: syncfuse
      POSTGRES_PASSWORD: syncfuse
    volumes:
      - syncfuse-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  cypress:
    image: "cypress/included:13.6.0"
    depends_on:
      - syncfuse
      - db
    environment:
      - CYPRESS_baseUrl=http://syncfuse:3000
      - CYPRESS_syncfuse_user=admin
      - CYPRESS_syncfuse_password=syncfuse
    volumes:
      - ./tsconfig.json:/tsconfig.json
      - ../cypress.config.ts:/cypress.config.ts
      - ./:/cypress
      - ../node_modules/:/node_modules
      - ../src/lib/crypto.ts:/src/lib/crypto.ts
volumes:
  syncfuse-db-data:
