name: Node.js CI

on: [push]

env:
  DATABASE_URL: "postgresql://user:pass@localhost:5432/dummy"
  SKIP_DB_CHECK: 1

jobs:
  build:
    if: github.repository == 'umami-software/umami'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: npm install --global pnpm
      - run: pnpm install
      - run: pnpm test
      - run: pnpm build
